## => Site Settings
##############################
url     : http://itrain.top
title   : itrain
description: >
  介绍HTML5大前端相关技术，传递前端热点信息

## => Author and Social
##############################
author:
  type      : person
  name      : isaac
  url       : http://itrain.top
  avatar    : /assets/images/avatar.png
  bio       : HTML5 前端工程师，平时喜欢逛逛技术论坛，整理一些个人笔记，空闲时间搞点新技术。
  email     : zhliro1102@gmail.com
  facebook  : # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter   : # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  weibo     : # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  telegram  : # "user_name" the last part of your profile url, e.g. https://t.me/user_name
  medium    : # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
  zhihu     : # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
  douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
  linkedin  : # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  github    : itrainhub
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name

## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: itrainhub/itrainhub.github.io
repository_tree: master

## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## => Paginate
##############################
paginate: 20
paginate_path: /page:num

## => Comments
##############################
comments:
  provider: valine

  ## Valine
  valine:
    app_id      : 3bxgEnYSeOD9ahnBY0WjDdBF-gzGzoHsz
    app_key     : n0CKGMrvPFgtAnOUY7vDY563
    placeholder : 请输入评论内容！
    lang        : 'zh-CN'
    avatar      : robohash

license: CC-BY-NC-4.0

## => Pageview
##############################
pageview:
  provider: leancloud

  ## Leancloud
  leancloud:
    app_id    : 3bxgEnYSeOD9ahnBY0WjDdBF-gzGzoHsz
    app_key   : n0CKGMrvPFgtAnOUY7vDY563
    app_class : blog

## => Search
##############################
search:
  provider: default
  
## => Analytics
##############################
analytics:
  provider: google

  ## Google Analytics
  google:
    tracking_id : UA-163557335-1
    anonymize_ip: false # Anonymize IP tracking for Analytics

## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : /:year/:month/:title/

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - itrain_blog.gemspec

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: false
      show_subscribe: true
      pageview: true

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-minifier
  - jekyll-last-modified-at

jekyll-minifier:
  uglifier_args:
    harmony: true
